### ISSUE TITLE
More advanced examples

### ISSUE THREAD

**Issue by iahung3** [tishion/potto#14]
That could showcase the full power of Potto. A list of real-world projects that are using Potto is awesome, too.

**Comment by tishion** [comment]
https://start.qq.com/download.html Windows Platform

**Comment by tishion** [comment]
Hi @iahung3 , I have to say, there is no very amazing power of Potto, I develop this tool only for one purpose, that is:
decoupling the development of large-scale software project, especially for the platform-like software. Potto provides a clear way to design and implement a Plugin-Host architecture. 

For example, we are creating a new software product which contains a lot of different feature modules, and we have different team for different module. If we cannot decouple the module at compiling time, that means we cannot build a single module without its dependency modules. But with Potto, you can design a Plugin-Host architecture and encapsulate module into plugin. for one module development team, they just need to work on their own plugin project without dependency of other plugin(team).
