### ISSUE TITLE
https://tishion.github.io/ Site not found

### ISSUE THREAD

**Issue by nsgnkhibdk2cls0f** [tishion/potto#3]
This is the only thing I saw.

> 404
> There isn't a GitHub Pages site here.
> 
> If you're trying to publish one, [read the full documentation](https://help.github.com/pages/) to learn how to set up GitHub Pages for your repository, organization, or user account.
> 
> [GitHub Status](https://githubstatus.com/) — [@githubstatus](https://twitter.com/githubstatus)

**Comment by tishion** [comment]
https://tishion.github.io/potto/ 

this works

**Comment by nsgnkhibdk2cls0f** [comment]
> https://tishion.github.io/potto/
> 
> this works

This doesn't: https://tishion.github.io/Potto/document/html/index.html but this works:

https://tishion.github.io/potto/document/html/index.html

You will have to update https://tishion.github.io/potto/ to incorporate this change :wink:
