### ISSUE TITLE
What's the point of potto?

### ISSUE THREAD

**Issue by nsgnkhibdk2cls0f** [tishion/potto#4]
Isn't COM supposed to share objects between different programming languages? potto is implemented in C++ and can only be used with C++ (at least this is my conclusion after reading the examples). So what's the point of it? For fun? Why don't just use C++'s native objects since potto is C++ only anyway?

https://en.wikipedia.org/wiki/Component_Object_Model

**Comment by tishion** [comment]
Hi @nsgnkhibdk2cls0f 

 > Isn't COM supposed to share objects between different programming languages? 

You are correct, COM enables you to share the object/functionality between different programming languages. More accurate explanation is COM enables the re-using of software components at binary level. You just acquire then component and consume it without considering which language it is implemented with. 

> potto is implemented in C++ and can only be used with C++ (at least this is my conclusion after reading the examples).

Potto is implemented in C++ and is not aiming at the complete concepts or features of MS COM. It only extracts some features from MS COM below:
 - interface abstraction 
 - the way to define/implement object/interface, everything with an identity (GUID or simple unique string)
 - the way to manage component/object/interface, components registry library (xml file), object pool (runtime cache), interface lookup map

> So what's the point of it? For fun? 

From my personal perspective, this is not for fun. Potto was created to provide an easy way to decouple the modules in C++ projects at both compiling time and runtime. Let's say if you are going to create a C++ project and you want to implement a platform-plugin framework, you can just introduce potto to achieve this. or you can choose to implement a new plugin host, define your plugin interface, then you need to consider how to organize the plugins module projects and output artifacts. Maybe my explanation is not very clear to you, but in short word: potto is a supper-min subset of MS COM concept. 

Potto has been applied in live product for years.
