### ISSUE TITLE
Use C++ standard library's <filesystem> when possible

### ISSUE THREAD

**Issue by iahung2** [tishion/potto#9]
Check if the compiler supports C++17. If the compiler supports C++17 then use C++ standard library's `<filesystem>` instead of `<ghc/filesystem.hpp>`.

**Comment by tishion** [comment]
I hope this PR can solve your problems
#10 

BTW, I have no enough time to keep work on this project, if you are willing to contribute, I will appreciate it. or you can fork and do whatever you need. 

Thanks！
